### PR TITLE
Enable usage of 'x-real-ip' and 'x-forwarded-for' header fields

### PR DESCRIPTION
**Pull request by tobilg**

### CODE REVIEW

**Comment by bahamas10** [comment]
This is already support for the `:Xip` format identifier... from the readme:

- `ip`: The remote IP
- `Xip`: The remote IP, using X-Forwarded-For if set

**Comment by tobilg** [comment]
Sorry, missed that part... But :Xip doesn’t seem to cover x-real-ip as of https://github.com/bahamas10/node-access-log/blob/master/index.js#L68 I think it would make eventually sense to add that as well @bahamas10

**Comment by bahamas10** [comment]
thanks! x-real-ip is now checked first for :Xip 

```
$ npm publish
+ access-log@0.4.1
```

**Comment by tobilg** [comment]
Thank you very much!

**Pull request closed without merging**
